const test=require('node:test'),assert=require('node:assert/strict'),D=require('../web/maintenance-data.js');
const row=(id,passed,split='holdout',mode='offline')=>({id,passed,split,mode});
const report=(a,b)=>({test_set:'ds',test_set_sha256:'a',catalog_sha256:'b',rows:{v1:a,v2:b}});
test('denominator and percentage points use aligned cases',()=>{const c=D.compare(report([row('A',false),row('B',true)],[row('B',true),row('A',true)]));assert.equal(c.points,50);assert.equal(c.delta,1);assert.equal(c.changes.改善,1)});
test('historical grouped totals match case results',()=>{const r=require('../reports/evaluation.json');const all=D.compare(r),dev=D.compare(r,[],'v1','v2','development'),hold=D.compare(r,[],'v1','v2','holdout');assert.equal(all.left.total,dev.left.total+hold.left.total);assert.equal(all.left.passed,dev.left.passed+hold.left.passed);assert.equal(all.points,6.25);assert.equal(hold.points,6.25)});
test('missing report does not yield success',()=>{const c=D.compare();assert.equal(c.comparable,false);assert.equal(c.points,null);assert.equal(c.right.total,0)});
test('zero successes and all failures stay zero',()=>{const c=D.compare(report([row('A',false)],[row('A',false)]));assert.equal(c.right.passed,0);assert.equal(c.points,0)});
test('skipped is included in denominator but not successes',()=>{const c=D.compare(report([row('A',true)],[{...row('A',true),skipped:true}]));assert.equal(c.right.total,1);assert.equal(c.right.notRun,1);assert.equal(c.right.passed,0);assert.equal(c.points,null)});
test('different IDs cannot look like improvement',()=>{const c=D.compare(report([row('A',false)],[row('B',true)]));assert.equal(c.changes.不可比较,2);assert.equal(c.points,null)});
test('duplicate IDs are not counted as comparable',()=>{const c=D.compare(report([row('A',false),row('A',false)],[row('A',true)]));assert.equal(c.comparable,false)});
test('execution modes and models cannot mix',()=>{for(const right of [{...row('A',true),mode:'live'},{...row('A',true),traces:[{model:'other'}]}])assert.equal(D.compare(report([row('A',false)],[right])).comparable,false)});
test('missing identity and group mismatch cannot compare',()=>{const r=report([row('A',false)],[row('A',true,'development')]);assert.equal(D.compare(r).comparable,false);delete r.test_set_sha256;assert.equal(D.compare(r).points,null)});
test('same selected version is not an experiment',()=>assert.equal(D.compare(report([row('A',true)],[]),[],'v1','v1').comparable,false));
test('duration distinguishes missing and zero',()=>{assert.equal(D.duration(0),'0 ms');for(const v of [null,undefined,'0',-1,NaN])assert.equal(D.duration(v),'—');assert.equal(D.duration(1200),'1.2 s')});
test('cost distinguishes no call, missing and actual zero',()=>{assert.equal(D.callInfo({model_calls:0}).cost,'未调用模型');assert.equal(D.callInfo({model_calls:1}).cost,'未记录');assert.match(D.callInfo({model_calls:1,estimated_cost_usd:0,usage_reports:[{total_tokens:0}]}).cost,/0.000000/);assert.equal(D.callInfo({}).calls,'未记录')});
test('filter statistics and median are scoped and omit unknown',()=>{const rows=[{task_id:'a',status:'failed',latency_ms:0},{task_id:'a',status:'success',latency_ms:10},{task_id:'b',status:'success'}];assert.deepEqual(D.runStats(D.filterRuns(rows,{task:'a'})),{count:2,failed:1,median:5,timed:2});assert.equal(D.runStats([]).median,null)});
test('case filters handle all, improved, failed and pending',()=>{const rows=D.compare(report([row('A',false),row('B',false),row('C',true)],[row('A',true),row('B',false),row('C',false)])).rows;assert.equal(D.filterCases(rows,'全部').length,3);assert.equal(D.filterCases(rows,'改善').length,1);assert.equal(D.filterCases(rows,'仍失败').length,1);assert.equal(D.filterCases(rows,'待处理').length,2)});
test('semantic statuses do not claim purchases',()=>{assert.equal(D.status({status:'success'}),'执行完成');assert.equal(D.status({type:'checkout',status:'success'}),'入口已创建');assert.equal(D.operation({type:'purchase_jump'}),'打开购买链接')});
test('large long input and missing fields remain calculable',()=>{const rows=Array.from({length:1000},(_,i)=>({id:String(i),input:'长'.repeat(3000),latency_ms:i%2===0?i:null,status:'success'}));assert.equal(D.runStats(rows).count,1000);assert.equal(D.runStats(rows).timed,500);assert.equal(D.operation({}),'未记录操作摘要')});
test('top-level model, catalog and missing group block comparison',()=>{for(const update of [{model:'different'},{catalog_version:'different'},{split:undefined}])assert.equal(D.compare(report([row('A',false)],[{...row('A',true),...update}])).comparable,false)});
test('saved report summaries agree with actual group rows',()=>{const r=require('../reports/evaluation.json');for(const v of Object.keys(r.rows))for(const split of ['development','holdout']){const rows=r.rows[v].filter(x=>x.split===split),s=r.summaries[v][split];assert.equal(s.total,rows.length);assert.equal(s.passed,rows.filter(x=>x.passed===true).length);assert.equal(s.failed,rows.filter(x=>x.passed===false).length)}});


test('CNY estimates preserve real zero and missing usage',()=>{assert.match(D.callInfo({model_calls:2,estimated_cost_cny:0}).cost,/¥ 0.000000/);assert.equal(D.callInfo({model_calls:2}).cost,'未记录');assert.match(D.callInfo({model_calls:1,estimated_cost_cny:0.012}).cost,/0.012000/)});
